export default [
    {
      "color-scheme": "light",
      "primary": "#570df8",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "secondary-content": "#ffffff",
      "accent": "#37cdbe",
      "accent-content": "#163835",
      "neutral": "#3d4451",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#f9fafb",
      "base-300": "#d1d5db",
      "base-content": "#1f2937",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "light"
    },
    {
      "color-scheme": "dark",
      "primary": "#793ef9",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "secondary-content": "#ffffff",
      "accent": "#37cdbe",
      "accent-content": "#163835",
      "neutral": "#2a2e37",
      "neutral-content": "#ffffff",
      "base-100": "#3d4451",
      "base-200": "#2a2e37",
      "base-300": "#16181d",
      "base-content": "#ebecf0",
      "info": "#66c7ff",
      "success": "#87d039",
      "warning": "#e2d562",
      "error": "#ff6f6f",
      "theme": "dark"
    },
    {
      "color-scheme": "light",
      "primary": "#65c3c8",
      "primary-content": "#ffffff",
      "secondary": "#ef9fbc",
      "secondary-content": "#ffffff",
      "accent": "#eeaf3a",
      "accent-content": "#ffffff",
      "neutral": "#291334",
      "neutral-content": "#ffffff",
      "base-100": "#faf7f5",
      "base-200": "#efeae6",
      "base-300": "#e7e2df",
      "base-content": "#291334",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626",
      "theme": "cupcake"
    },
    {
      "color-scheme": "light",
      "primary": "#e0a82e",
      "primary-content": "#181830",
      "secondary": "#f9d72f",
      "secondary-content": "#181830",
      "accent": "#181830",
      "accent-content": "#ffffff",
      "neutral": "#181830",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#f9fafb",
      "base-300": "#d1d5db",
      "base-content": "#181830",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "bumblebee"
    },
    {
      "color-scheme": "light",
      "primary": "#66cc8a",
      "primary-content": "#ffffff",
      "secondary": "#377cfb",
      "secondary-content": "#ffffff",
      "accent": "#ea5234",
      "accent-content": "#ffffff",
      "neutral": "#333c4d",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#f9fafb",
      "base-300": "#d1d5db",
      "base-content": "#333c4d",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "emerald"
    },
    {
      "color-scheme": "light",
      "primary": "#4b6bfb",
      "primary-content": "#ffffff",
      "secondary": "#7b92b2",
      "secondary-content": "#ffffff",
      "accent": "#67cba0",
      "accent-content": "#ffffff",
      "neutral": "#181a2a",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#f9fafb",
      "base-300": "#d1d5db",
      "base-content": "#181a2a",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "theme": "corporate"
    },
    {
      "color-scheme": "dark",
      "primary": "#e779c1",
      "primary-content": "#2d1b69",
      "secondary": "#58c7f3",
      "secondary-content": "#2d1b69",
      "accent": "#f3cc30",
      "accent-content": "#2d1b69",
      "neutral": "#20134e",
      "neutral-content": "#f9f7fd",
      "base-100": "#2d1b69",
      "base-200": "#20134e",
      "base-300": "#140a2e",
      "base-content": "#f9f7fd",
      "info": "#53c0f3",
      "success": "#71ead2",
      "warning": "#f3cc30",
      "error": "#e24056",
      "theme": "synthwave"
    },
    {
      "color-scheme": "light",
      "primary": "#ef9995",
      "primary-content": "#282425",
      "secondary": "#a4cbb4",
      "secondary-content": "#282425",
      "accent": "#ebdc99",
      "accent-content": "#282425",
      "neutral": "#7d7259",
      "neutral-content": "#e4d8b4",
      "base-100": "#e4d8b4",
      "base-200": "#d2c59d",
      "base-300": "#c6b386",
      "base-content": "#282425",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626",
      "theme": "retro"
    },
    {
        "color-scheme": "dark",
        "primary": "#ff7518",
        "primary-content": "#ffffff",
        "secondary": "#000000",
        "secondary-content": "#ffffff",
        "accent": "#ffcc00",
        "neutral": "#111111",
        "base-100": "#1a1a1a",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "halloween"
      },
      {
        "color-scheme": "light",
        "primary": "#ff85a2",
        "primary-content": "#ffffff",
        "secondary": "#ffc2d1",
        "secondary-content": "#ffffff",
        "accent": "#ffacc0",
        "neutral": "#7a5475",
        "base-100": "#fff5f7",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "valentine"
      },
      {
        "color-scheme": "dark",
        "primary": "#ff00ff",
        "primary-content": "#000000",
        "secondary": "#00ffff",
        "secondary-content": "#000000",
        "accent": "#ff9900",
        "neutral": "#222222",
        "base-100": "#111111",
        "info": "#00ffff",
        "success": "#00ff00",
        "warning": "#ffcc00",
        "error": "#ff0033",
        "theme": "cyberpunk"
      },
      {
        "color-scheme": "light",
        "primary": "#8cc084",
        "primary-content": "#ffffff",
        "secondary": "#c2e1c2",
        "secondary-content": "#ffffff",
        "accent": "#f3c677",
        "neutral": "#556b2f",
        "base-100": "#e9f5dc",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "garden"
      },
      {
        "color-scheme": "dark",
        "primary": "#1e5631",
        "primary-content": "#ffffff",
        "secondary": "#4a7c59",
        "secondary-content": "#ffffff",
        "accent": "#a1cf6b",
        "neutral": "#2e2e2e",
        "base-100": "#1b1b1b",
        "info": "#66c7ff",
        "success": "#87d039",
        "warning": "#e2d562",
        "error": "#ff6f6f",
        "theme": "forest"
      },
      {
        "color-scheme": "dark",
        "primary": "#09ecf3",
        "primary-content": "#005355",
        "secondary": "#966fb3",
        "secondary-content": "#ffffff",
        "accent": "#ffe999",
        "neutral": "#3b8ac4",
        "base-100": "#345da7",
        "info": "#2563eb",
        "success": "#16a34a",
        "warning": "#d97706",
        "error": "#dc2626",
        "theme": "aqua"
      },
      {
        "color-scheme": "light",
        "primary": "#f8f8f8",
        "primary-content": "#111111",
        "secondary": "#d1d1d1",
        "secondary-content": "#111111",
        "accent": "#b3b3b3",
        "neutral": "#111111",
        "base-100": "#ffffff",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "wireframe"
      },
      {
        "color-scheme": "dark",
        "primary": "#000000",
        "primary-content": "#ffffff",
        "secondary": "#1a1a1a",
        "secondary-content": "#ffffff",
        "accent": "#333333",
        "neutral": "#222222",
        "base-100": "#000000",
        "info": "#3abff8",
        "success": "#36d399",
        "warning": "#fbbd23",
        "error": "#f87272",
        "theme": "black"
      },
      {
        "color-scheme": "light",
        "primary": "#ff69b4",
        "primary-content": "#ffffff",
        "secondary": "#ff1493",
        "secondary-content": "#ffffff",
        "accent": "#ff4500",
        "neutral": "#2c2f33",
        "base-100": "#ffe4e1",
        "info": "#1e90ff",
        "success": "#32cd32",
        "warning": "#ff8c00",
        "error": "#dc143c",
        "theme": "pink"
      },
      {
        "color-scheme": "dark",
        "primary": "#ff6347",
        "primary-content": "#ffffff",
        "secondary": "#ff4500",
        "secondary-content": "#ffffff",
        "accent": "#ffa500",
        "neutral": "#222222",
        "base-100": "#2f4f4f",
        "info": "#87ceeb",
        "success": "#228b22",
        "warning": "#ffeb3b",
        "error": "#ff0000",
        "theme": "volcano"
      },
      {
        "color-scheme": "light",
        "primary": "#8b0000",
        "primary-content": "#ffffff",
        "secondary": "#800000",
        "secondary-content": "#ffffff",
        "accent": "#b22222",
        "neutral": "#282c34",
        "base-100": "#fff5f5",
        "info": "#4682b4",
        "success": "#008000",
        "warning": "#ffcc00",
        "error": "#b22222",
        "theme": "ruby"
      },
      {
        "color-scheme": "dark",
        "primary": "#4b0082",
        "primary-content": "#ffffff",
        "secondary": "#800080",
        "secondary-content": "#ffffff",
        "accent": "#dda0dd",
        "neutral": "#222222",
        "base-100": "#301934",
        "info": "#7b68ee",
        "success": "#32cd32",
        "warning": "#ff8c00",
        "error": "#dc143c",
        "theme": "indigo"
      },
      {
        "color-scheme": "light",
        "primary": "#00bcd4",
        "primary-content": "#ffffff",
        "secondary": "#0097a7",
        "secondary-content": "#ffffff",
        "accent": "#26c6da",
        "neutral": "#37474f",
        "base-100": "#e0f7fa",
        "info": "#00acc1",
        "success": "#00c853",
        "warning": "#ff9100",
        "error": "#d50000",
        "theme": "cyan"
      }
    
]
  